jobs:
      - deployment: create
        displayName: Create deployment
        environment: $(ENVIRONMENT)
        variables:
          plan_providers: $[ stageDependencies.Plan.plan.outputs['validate.providers'] ]
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - checkout: self
                  displayName: Checkout
                  fetchDepth: 1
                  persistCredentials: true

                - task: AzureCLI@2
                  displayName: Install tools
                  env:
                    IN_SEVERITY: $(LOG_SEVERITY)
                    IN_TEMPLATE: $(TEMPLATE)
                    LOG_NAME: install_tools
                    LOG_ORDER: b1
                    LOG_PATH: $(Pipeline.Workspace)/logs
                    SCRIPT: install-tools
                    VERSION: $(WORKFLOW_VERSION)
                  inputs:
                    azureSubscription: $(SERVICE_CONNECTION)
                    scriptLocation: inlineScript
                    scriptType: bash
                    inlineScript: |
                      uri="https://github.com/innofactororg/bicep-action/raw/${VERSION}/scripts/${SCRIPT}.sh"
                      HTTP_CODE=$(curl -sSL --remote-name --retry 4 \
                        --write-out "%{response_code}" \
                        --header 'Accept: application/vnd.github.raw' "${uri}"
                      )
                      if [ "${HTTP_CODE}" -lt 200 ] || [ "${HTTP_CODE}" -gt 299 ]; then
                        echo "##[error]Unable to get ${uri}! Response code: ${HTTP_CODE}"
                        exit 1
                      fi
                      chmod +x ${SCRIPT}.sh
                      ./${SCRIPT}.sh

                - task: AzureCLI@2
                  condition: and(succeeded(), not(eq(variables['plan_providers'], '')))
                  displayName: Check Azure providers
                  env:
                    IN_PROVIDERS: $(plan_providers)
                    IN_SEVERITY: $(LOG_SEVERITY)
                    LOG_NAME: check_providers
                    LOG_ORDER: b3
                    LOG_PATH: $(Pipeline.Workspace)/logs
                    SCRIPT: azure-providers
                    SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
                    VERSION: $(WORKFLOW_VERSION)
                    WAIT_COUNT: $(AZURE_PROVIDER_WAIT_COUNT)
                    WAIT_SECONDS: $(AZURE_PROVIDER_WAIT_SECONDS)
                  inputs:
                    azureSubscription: $(SERVICE_CONNECTION)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      if [[ "${IN_PROVIDERS}" == *plan_providers* ]]; then
                        echo 'Skip! The plan.validate.providers output has not been set!'
                        exit
                      fi
                      uri="https://github.com/innofactororg/bicep-action/raw/${VERSION}/scripts/${SCRIPT}.sh"
                      HTTP_CODE=$(curl -sSL --remote-name --retry 4 \
                        --write-out "%{response_code}" \
                        --header 'Accept: application/vnd.github.raw' "${uri}"
                      )
                      if [ "${HTTP_CODE}" -lt 200 ] || [ "${HTTP_CODE}" -gt 299 ]; then
                        echo "##[error]Unable to get ${uri}! Response code: ${HTTP_CODE}"
                        exit 1
                      fi
                      chmod +x ${SCRIPT}.sh
                      ./${SCRIPT}.sh

                - task: AzureCLI@2
                  displayName: Deploy
                  env:
                    IN_LOCATION: $(LOCATION)
                    IN_MANAGEMENT_GROUP: $(MANAGEMENT_GROUP)
                    IN_RESOURCE_GROUP: $(RESOURCE_GROUP)
                    IN_SCOPE: $(SCOPE)
                    IN_SEVERITY: $(LOG_SEVERITY)
                    IN_TEMPLATE: $(TEMPLATE)
                    IN_TEMPLATE_PARAMS: $(TEMPLATE_PARAMETERS)
                    LOG_NAME: deploy
                    LOG_ORDER: a1
                    LOG_PATH: $(Pipeline.Workspace)/logs
                    RUN_ID: $(Build.BuildId)
                    SCRIPT: az-deploy
                    SOURCE_PATH: $(Build.SourcesDirectory)
                    SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
                    VERSION: $(WORKFLOW_VERSION)
                  inputs:
                    azureSubscription: $(SERVICE_CONNECTION)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      uri="https://github.com/innofactororg/bicep-action/raw/${VERSION}/scripts/${SCRIPT}.sh"
                      HTTP_CODE=$(curl -sSL --remote-name --retry 4 \
                        --write-out "%{response_code}" \
                        --header 'Accept: application/vnd.github.raw' "${uri}"
                      )
                      if [ "${HTTP_CODE}" -lt 200 ] || [ "${HTTP_CODE}" -gt 299 ]; then
                        echo "##[error]Unable to get ${uri}! Response code: ${HTTP_CODE}"
                        exit 1
                      fi
                      chmod +x ${SCRIPT}.sh
                      ./${SCRIPT}.sh create

                - task: Bash@3
                  condition: and(always(), eq(variables['Build.Reason'], 'PullRequest'))
                  displayName: Add comment
                  env:
                    COMMENTS_URL: $(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=7.1-preview.1
                    COMMIT_SHA: $(System.PullRequest.SourceCommitId)
                    COMMIT_URL: $(System.CollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)/commit/$(System.PullRequest.SourceCommitId)
                    EVENT_ACTION: $(Build.Reason)
                    EVENT_ACTOR: $(Build.SourceVersionAuthor)
                    EVENT_NO: "[$(System.PullRequest.PullRequestId)]($(Build.BuildUri))"
                    JOB_NAME: $(Build.BuildNumber)
                    JOB_STATUS: $(Agent.JobStatus)
                    JOB_URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
                    LOG_NAME: deploy_comment
                    LOG_PATH: $(Pipeline.Workspace)/logs
                    RUN_NUMBER: $(Build.BuildId)
                    SCRIPT: pr-comment
                    TOKEN: $(System.AccessToken)
                    VERSION: $(WORKFLOW_VERSION)
                  inputs:
                    targetType: inline
                    script: |
                      export COMMIT_SHA="[${COMMIT_SHA:0:8}](${COMMIT_URL})"
                      uri="https://github.com/innofactororg/bicep-action/raw/${VERSION}/scripts/${SCRIPT}.sh"
                      HTTP_CODE=$(curl -sSL --remote-name --retry 4 \
                        --write-out "%{response_code}" \
                        --header 'Accept: application/vnd.github.raw' "${uri}"
                      )
                      if [ "${HTTP_CODE}" -lt 200 ] || [ "${HTTP_CODE}" -gt 299 ]; then
                        echo "##[error]Unable to get ${uri}! Response code: ${HTTP_CODE}"
                        exit 1
                      fi
                      chmod +x ${SCRIPT}.sh
                      ./${SCRIPT}.sh

                - task: Bash@3
                  condition: or(failed(), and(succeeded(), not(eq(variables['LOG_SEVERITY'], 'ERROR'))))
                  displayName: Show debug info
                  inputs:
                    targetType: inline
                    script: |
                      set -e
                      echo '##[group]environment variables'
                      for var in $(compgen -e); do
                        echo "${var} ${!var}"
                      done
                      echo '##[endgroup]'

                - task: PublishPipelineArtifact@1
                  displayName: Upload logs
                  condition: always()
                  inputs:
                    targetPath: $(Pipeline.Workspace)/logs
                    artifact: deploy_logs
                    publishLocation: pipeline
